# Generated by Django 4.2.2 on 2023-06-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
