# Generated by Django 4.2.2 on 2023-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0002_color_color_alter_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Kırmızı'), ('#0000FF', 'Mavi')], max_length=7),
        ),
    ]
