# Generated by Django 4.2.2 on 2023-06-08 11:38

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_article_article_image_alter_article_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(validators=[main.validators.validate_content], verbose_name='Content'),
        ),
    ]
